### ISSUE TITLE
Setup a licence

### ISSUE THREAD

**Issue by scotthosking** [scotthosking/get-station-data#3]
get input form @JimCircadian

**Comment by JimCircadian** [comment]
@scotthosking MIT is fine. If you're up for it, I can show you how to rewrite the git history to include the license in all revisions. It does rewrite the history, but it's probably worth doing

**Comment by scotthosking** [comment]
Hi @JimCircadian, only just saw this message - would be great to look at this at some point as the repo is having a new burst of life thanks to @magnusross

**Comment by JimCircadian** [comment]
I'll stick it in the list for next week and ping you a slack message. Shouldn't take long!

**Comment by scotthosking** [comment]
I've just added the MIT licence - no rush on the history revision update

**Comment by scotthosking** [comment]
I was also wondering the same - just leaving it and using the licence from here on. Thanks for looking into this
